# Generated by Django 4.0.5 on 2022-07-09 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliniq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliniq.patient'),
        ),
    ]
